// automatically generated by the FlatBuffers compiler, do not modify

package org.nuhara.demos.flatbuffer;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Request extends Table {
  public static Request getRootAsRequest(ByteBuffer _bb) { return getRootAsRequest(_bb, new Request()); }
  public static Request getRootAsRequest(ByteBuffer _bb, Request obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Request __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String mti() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mtiAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer mtiInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String rrn() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer rrnAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer rrnInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String message() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer messageAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer messageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createRequest(FlatBufferBuilder builder,
      int mtiOffset,
      int rrnOffset,
      int messageOffset) {
    builder.startObject(3);
    Request.addMessage(builder, messageOffset);
    Request.addRrn(builder, rrnOffset);
    Request.addMti(builder, mtiOffset);
    return Request.endRequest(builder);
  }

  public static void startRequest(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addMti(FlatBufferBuilder builder, int mtiOffset) { builder.addOffset(0, mtiOffset, 0); }
  public static void addRrn(FlatBufferBuilder builder, int rrnOffset) { builder.addOffset(1, rrnOffset, 0); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(2, messageOffset, 0); }
  public static int endRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

