// automatically generated by the FlatBuffers compiler, do not modify

package org.nuhara.demos.flatbuffer;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Response extends Table {
  public static Response getRootAsResponse(ByteBuffer _bb) { return getRootAsResponse(_bb, new Response()); }
  public static Response getRootAsResponse(ByteBuffer _bb, Response obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Response __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String mti() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mtiAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer mtiInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String rrn() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer rrnAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer rrnInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String responseCode() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer responseCodeAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer responseCodeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String authorizationCode() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer authorizationCodeAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer authorizationCodeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createResponse(FlatBufferBuilder builder,
      int mtiOffset,
      int rrnOffset,
      int responseCodeOffset,
      int authorizationCodeOffset) {
    builder.startObject(4);
    Response.addAuthorizationCode(builder, authorizationCodeOffset);
    Response.addResponseCode(builder, responseCodeOffset);
    Response.addRrn(builder, rrnOffset);
    Response.addMti(builder, mtiOffset);
    return Response.endResponse(builder);
  }

  public static void startResponse(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addMti(FlatBufferBuilder builder, int mtiOffset) { builder.addOffset(0, mtiOffset, 0); }
  public static void addRrn(FlatBufferBuilder builder, int rrnOffset) { builder.addOffset(1, rrnOffset, 0); }
  public static void addResponseCode(FlatBufferBuilder builder, int responseCodeOffset) { builder.addOffset(2, responseCodeOffset, 0); }
  public static void addAuthorizationCode(FlatBufferBuilder builder, int authorizationCodeOffset) { builder.addOffset(3, authorizationCodeOffset, 0); }
  public static int endResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

